### ISSUE TITLE
Abaqus Error: Problem during compilation - conc.f

### ISSUE THREAD

**Issue by yinjy0** [PoliHydra/hydra#2]
hello, Which Fortran compiler do you use? I meet a problem when I run"abaqus continue job=H-3cohesive user=conc.f". The log file shows 'ifort' is not an internal or external command, nor is it an executable program Or batch file.

**Comment by miccoli** [comment]
Unfortunately Abaqus is quite picky on the fortran compiler: officially only the Intel compiler is supported. You can find the required version in the *Abaqus Installation and Licensing Guide*. Manuals up to ver. 6.14 can be found on the 3DS site [here](https://www.3ds.com/products-services/simulia/services-support/support/documentation/).

By the way, `ifort` is the command name by which the Intel fortran is invoked.

**Comment by yinjy0** [comment]
thank you very much!
