### ISSUE TITLE
A question about the displacement in H-1static and H-3cohesive

### ISSUE THREAD

**Issue by yinjy0** [PoliHydra/hydra#3]
H-1static.inp shows
*BOUNDARY
 HOLE, 2, 2, 0.05
However, H-3cohesive.inp shows
*BOUNDARY
 HOLE, 2, 2, 0.22

Shouldn't the two values be the same? Looking forward to your reply.

**Comment by ChiaraColombo** [comment]
Hello,
the boundary condition of the first stress-strain analysis (0.05mm) is the maximum applied during the experimental test without inducing crack propagation. Indeed, this analysis does not consider cohesive elements. The third analysis, on the other hand, simulates crack propagation with cohesive elements, and the displacement is the total one as in the experimental test (0.22mm).
Best

**Comment by yinjy0** [comment]
> Hello,
> the boundary condition of the first stress-strain analysis (0.05mm) is the maximum applied during the experimental test without inducing crack propagation. Indeed, this analysis does not consider cohesive elements. The third analysis, on the other hand, simulates crack propagation with cohesive elements, and the displacement is the total one as in the experimental test (0.22mm).
> Best

Thanks for your answer
